version: "3.9"  # optional since v1.27.0
services:
  pgdb:
    image: "postgres:latest"
    ports:
    - 5432:5432
    environment:
      - POSTGRES_USER=dbuser # The PostgreSQL user (useful to connect to the database)
      - POSTGRES_PASSWORD=dbpass # The PostgreSQL password (useful to connect to the database)
      - POSTGRES_DB=default_db # The PostgreSQL default database (automatically created at first launch)      
    volumes:
    - pgdata:/var/lib/postgresql/data/

volumes:
    pgdata:
        external: true